# Generated by Django 4.2.29 on 2026-03-31 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0003_productvariant_alter_category_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_qty", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("restock", "Restock"),
                            ("manual", "Manual"),
                            ("order_cancelled", "Order Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_changes",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_changes",
                        to="products.productvariant",
                    ),
                ),
            ],
        ),
    ]
